promise.then(f1).catch(f2);
promise.then(f1, f2); // в этом случае ошибка в f1 обработана не будет